project:
  type: website
  #output-dir: docs
website:
  title: "L'Œuvre"
  #title: "Oeuvre"
  #site-url: "http://localhost:3221/"
  #site-url: "fortunewalla.net"
  #site-url: "/" # needed else the RSS feed repeats the domain name twice in the url
  favicon: favicon.png
  #google-analytics: "G-"
  
  navbar:
    right:
      - text: " "
        icon: question-circle
        href: about.qmd
      - icon: rss
        href: index.xml
      #- icon: github
      #  href: https://github.com/
      #- icon: twitter
      #  href: https://twitter.com
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



